[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32
board = esp32s3box
framework = arduino
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216

build_flags = 
    -DBOARD_HAS_PSRAM
    -DLV_CONF_INCLUDE_SIMPLE
    -I src/

lib_deps =
    lovyan03/LovyanGFX@^1.1.12
    lvgl/lvgl@^8.3.11 ; Need version 8 for compatibility with existing examples, can update to 9 later
    https://github.com/TAMC-Maker/TAMC_GT911.git
    https://github.com/lewisxhe/ESP_IOExpander_Library.git

monitor_speed = 115200
upload_speed = 921600
